spring:
  application:
    name: Todo Application
  datasource:
    url: jdbc:h2:mem:testdb;  # In-memory database
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update # Automatically creates and updates database schema
      dialect: org.hibernate.dialect.H2Dialect
    show-sql: true
  h2:
    console:
      enabled: false # Enable H2 console for debugging
      path: h2/console

# Server configuration
server:
  port: 8080

# Spring Boot Actuator
management:
  endpoints:
    web:
      exposure:
        include: "health, metrics, info"    # Exposing common actuator endpoints only.
  endpoint:
    health:
      show-details: always